name: astr558
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy >= 1.22
  - scipy
  - astropy
  - pandas
  - matplotlib
  - jupyter
  - jupyterlab
  - ipython
  - tqdm
  - emcee
  - corner
  - pip
  - pip:
    - batman-package
    - rebound
