name: astr511
channels:
  - defaults
  - conda-forge
  - astropy
dependencies:
  - python
  - numpy
  - astropy
  - astroquery
  - pandas
  - scipy
  - matplotlib
  - jupyter
  - jupyterlab
  - ipython
  - astroML
  - scikit-learn