name: astr511
channels:
  - defaults
  - conda-forge
  - astropy
dependencies:
  - python
  - pip
  - numpy
  - numba
  - pytables
  - astropy
  - astroquery
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipython
  - astroML
  - scikit-learn
  - emcee
  - h5py
  - pip:
    - isochrones
    - gala